import { TbBrandNextjs } from "react-icons/tb";
import {
  SiBun,
  SiCss3,
  SiCypress,
  SiExpress,
  SiGmail,
  SiHtml5,
  SiJavascript,
  SiMicrosoftteams,
  SiMongodb,
  SiNestjs,
  SiNotion,
  SiPrisma,
  SiReacthookform,
  SiReactquery,
  SiTailwindcss,
  SiTypescript,
  SiZod,
} from "react-icons/si";
import { FaGithub, FaGit, FaNodeJs, FaReact } from "react-icons/fa";
export const stackConfig = [
  { icon: <TbBrandNextjs className="2xl:w-5 2xl:h-5 h-4 w-4" />, name: "Next.js" },
  { icon: <SiNestjs className="2xl:w-5 2xl:h-5 h-4 w-4" />, name: "Nest.js" },
  { icon: <FaReact className="2xl:w-5 2xl:h-5 h-4 w-4" />, name: "React.js" },
  { icon: <SiTypescript className="2xl:w-5 2xl:h-5 h-4 w-4" />, name: "TypeScript" },
  { icon: <SiJavascript className="2xl:w-5 2xl:h-5 h-4 w-4" />, name: "JavaScript" },
  { icon: <SiTailwindcss className="2xl:w-5 2xl:h-5 h-4 w-4" />, name: "Tailwind CSS" },
  { icon: <SiMongodb className="2xl:w-5 2xl:h-5 h-4 w-4" />, name: "MongoDB" },
  { icon: <FaGit className="2xl:w-5 2xl:h-5 h-4 w-4" />, name: "Git" },
  { icon: <FaGithub className="2xl:w-5 2xl:h-5 h-4 w-4" />, name: "GitHub" },
  { icon: <SiExpress className="2xl:w-5 2xl:h-5 h-4 w-4" />, name: "Express.js" },
  { icon: <FaNodeJs className="2xl:w-5 2xl:h-5 h-4 w-4" />, name: "Node.js" },
  { icon: <SiBun className="2xl:w-5 2xl:h-5 h-4 w-4" />, name: "Bun" },
  { icon: <SiCypress className="2xl:w-5 2xl:h-5 h-4 w-4" />, name: "Cypress" },
  { icon: <SiZod className="2xl:w-5 2xl:h-5 h-4 w-4" />, name: "Zod" },
  { icon: <SiHtml5 className="2xl:w-5 2xl:h-5 h-4 w-4" />, name: "HTML5" },
  { icon: <SiCss3 className="2xl:w-5 2xl:h-5 h-4 w-4" />, name: "CSS3" },
  { icon: <SiPrisma className="2xl:w-5 2xl:h-5 h-4 w-4" />, name: "Prisma" },
  { icon: <SiReacthookform className="2xl:w-5 2xl:h-5 h-4 w-4" />, name: "React Hook Form" },
  { icon: <SiReactquery className="2xl:w-5 2xl:h-5 h-4 w-4" />, name: "React Query" },
  { icon: <SiNotion className="2xl:w-5 2xl:h-5 h-4 w-4" />, name: "Notion" },
  { icon: <SiGmail className="2xl:w-5 2xl:h-5 h-4 w-4" />, name: "Gmail" },
  { icon: <SiMicrosoftteams className="2xl:w-5 2xl:h-5 h-4 w-4" />, name: "Microsoft Teams" },
];
