import { TbBrandNextjs } from "react-icons/tb";
import {
  SiBun,
  SiCss3,
  SiCypress,
  SiExpress,
  SiGmail,
  SiHtml5,
  SiJavascript,
  SiMicrosoftteams,
  SiMongodb,
  SiNestjs,
  SiNotion,
  SiPrisma,
  SiReacthookform,
  SiReactquery,
  SiTailwindcss,
  SiTypescript,
  SiZod,
} from "react-icons/si";
import { FaGithub, FaGit, FaNodeJs, FaReact } from "react-icons/fa";
export const stackConfig = [
  { icon: <TbBrandNextjs /> },
  { icon: <SiNestjs /> },
  { icon: <FaReact /> },
  { icon: <SiTypescript /> },
  { icon: <SiJavascript /> },
  { icon: <SiTailwindcss /> },
  { icon: <SiMongodb /> },
  { icon: <FaGit /> },
  { icon: <FaGithub /> },
  { icon: <SiExpress /> },
  { icon: <FaNodeJs /> },
  { icon: <SiBun /> },
  { icon: <SiCypress /> },
  { icon: <SiZod /> },
  { icon: <SiHtml5 /> },
  { icon: <SiCss3 /> },
  { icon: <SiPrisma /> },
  { icon: <SiReacthookform /> },
  { icon: <SiReactquery /> },
  { icon: <SiNotion /> },
  { icon: <SiGmail /> },
  { icon: <SiMicrosoftteams /> },
];
